### ISSUE TITLE
Level navigation is broken on firefox

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#301]
Using firefox on a mac I can't select level 1 and when I scroll to the bottom the planet overlaps the area it's displayed within.

<img width="1220" alt="te" src="https://user-images.githubusercontent.com/32912678/45114277-914feb00-b11a-11e8-930a-4e39ccc4e4dd.png">
<img width="629" alt="math_bot 2" src="https://user-images.githubusercontent.com/32912678/45114279-914feb00-b11a-11e8-9b2c-f0a78057bd78.png">

**Comment by giftedprimate** [comment]
@JWWeatherman Fix merged to master (#313) and deployed to pre prod, ready for inspection.

**Comment by JWWeatherman** [comment]
Still seeing the problem with the bottom tile if it is slightly hidden. Lose the ability to click and scroll.

https://drive.google.com/file/d/1F1zELAbLJUltwdmHvRSrNtEVp7IY_jCb/view?usp=sharing

**Comment by giftedprimate** [comment]
@JWWeatherman Fixed deployed to preprod, ready to be inspected.

**Comment by giftedprimate** [comment]
Deployed to prod, leaving open so JW can inspect at a later time.

**Comment by JWWeatherman** [comment]
Very nice!
